const ShopActionTypes = {
    FECTH_COLLECTIONS_START :'FECTH_COLLECTIONS_START',
    FECTH_COLLECTIONS_SUCCESS:'FECTH_COLLECTIONS_SUCCESS',
    FECTH_COLLECTIONS_FAILURE:'FETCH_COLLECTION_FAILURE'
}

export default ShopActionTypes;